### ISSUE TITLE
Can't to compile

### ISSUE THREAD

**Issue by brothermechanic** [starseeker/meshlab#2]
Hello
Thank you for cmake integration.
Help me to compile it
This is end of log http://paste.org.ru/?85aj8u
config http://paste.org.ru/?or7vi3
Thank you.

**Comment by starseeker** [comment]
I just pushed a few changes which should help - I'm in the process of updating, and not all the plugins have been fixed yet.

**Comment by starseeker** [comment]
OK, all the enabled plugins build - I don't have all of them enabled, and I've not tested some of the changes I've made for functionality, but it does at least build here.
